<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Cryptum\\NFT\\Admin\\AdminSettings' => $baseDir . '/src/Admin/AdminSettings.php',
    'Cryptum\\NFT\\Admin\\OrderSettings' => $baseDir . '/src/Admin/OrderSettings.php',
    'Cryptum\\NFT\\Admin\\ProductEditPage' => $baseDir . '/src/Admin/ProductEditPage.php',
    'Cryptum\\NFT\\CheckoutPage' => $baseDir . '/src/CheckoutPage.php',
    'Cryptum\\NFT\\PluginInit' => $baseDir . '/src/PluginInit.php',
    'Cryptum\\NFT\\ProductInfoPage' => $baseDir . '/src/ProductInfoPage.php',
    'Cryptum\\NFT\\Utils\\AddressValidator' => $baseDir . '/src/Utils/AddressValidator.php',
    'Cryptum\\NFT\\Utils\\Api' => $baseDir . '/src/Utils/Api.php',
    'Cryptum\\NFT\\Utils\\Blockchain' => $baseDir . '/src/Utils/Blockchain.php',
    'Cryptum\\NFT\\Utils\\Db' => $baseDir . '/src/Utils/Db.php',
    'Cryptum\\NFT\\Utils\\Log' => $baseDir . '/src/Utils/Log.php',
    'Cryptum\\NFT\\Utils\\Misc' => $baseDir . '/src/Utils/Misc.php',
    'Symfony\\Polyfill\\Mbstring\\Mbstring' => $vendorDir . '/symfony/polyfill-mbstring/Mbstring.php',
    'kornrunner\\Keccak' => $vendorDir . '/kornrunner/keccak/src/Keccak.php',
);
